name: FabianoPhotos
favicon: null
layout_spectrum: 0.07755578495562077
typography_spectrum: 0.0935491758864373
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.21184773417189717
  lightness: 0.937624730868265
  saturation: 0.22714788746088743
  rhythmicContrast: 0.8332986966706812
purpose: []
