name: FabianoPhotos
favicon: null
layout_spectrum: 0.07755578495562077
typography_spectrum: 0.0935491758864373
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#42394c'
    - '#795b5f'
    - '#0d0a08'
    - '#d48557'
    - '#ffca6a'
  brandStrength: 0.375
  lightness: 0.937624730868265
  saturation: 0.1875
  rhythmicContrast: 0.8332986966706812
purpose: []
